### ISSUE TITLE
Max size

### ISSUE THREAD

**Issue by bhack** [tsmetana/spotify-tray#24]
Sometime we hare very long titles. Can we have a max size param for the widget?

**Comment by tsmetana** [comment]
I played with this and it's actually not as easy as I would want... The tooltip is not an usual widget so I can actually only limit the length of the text. I tried and the result is rather ugly since the variable-width font make it difficult to guess how long each line should be. I'll keep tinkering but I don't feel like adding too much code because of this.

**Comment by tsmetana** [comment]
OK... I have not found a simple way to do this. Sorry.

**Comment by bhack** [comment]
Can you break the text in multiple parts if too long and change the text in the tooltil with a small timeout? So that we could rotate the content
