### ISSUE TITLE
No system tray icon on ElementaryOS

### ISSUE THREAD

**Issue by BananaManCJ** [tsmetana/spotify-tray#6]
No system tray icon is displayed on ElementaryOS. The system tray it uses is ayatana.

**Comment by tsmetana** [comment]
Isn't this on purpose? AFAIK ElementaryOS is just like Gnome: they simply don't want their users to use some features so they simply remove them. I can't do much about it. The GtkStatusIcon widget has been marked as "deprecated" (since GTK is essentially Gnome these days) so spotify-tray only works in environments where the developers are less aggressive with feature removals.
